export {default as Games} from "./Games"
export {default as Home} from "./Home"
export {default as Leaderboard} from "./Leaderboard"
export {default as Login} from "./Login"
export {default as Profile} from "./Profile"
export {default as Register} from "./Register"